version: '3.9'

services:
  minio:
    image: minio/minio:RELEASE.2024-03-10T02-53-48Z
    container_name: minio
    ports:
      - "9090:9090"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    tty: true
    entrypoint: sh
    command: -c "minio server --console-address ":9090" /export"
    volumes:
      - ./minio/data:/export

